name: ğŸš€ Continuous Integration
on: [push, pull_request]
jobs:
  test:
    name: ğŸ‰ Tests and Linters
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get the latest code
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: "16.14.2"

      - name: Install dependencies
        run: npm install

      - name: ğŸ§ª Run tests
        run: npm test

      - name: ğŸ“ Run linter
        run: npm run lint
